# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Crawler
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  Craw:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r requirement.txt
    - name: Konachan
      run: |
        python3 konachan.py
    - name: Safebooru
      run: |
        python3 safebooru.py
    - name: commit
      run: |
        git pull
        git config --global user.email akarachen@outlook.com
        git config --global user.name akarachen
        git add .
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
